---
#-------------------------- BASE INFORMATION --------------------------#
name: ecos
description: "Mobile application for the Ecos system "

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

#-------------------------- PRODUCTION PACKAGES --------------------------#
dependencies:
  flutter:
    sdk: flutter

#-------------------------- DEVELOPMENT PACKAGES --------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

#-------------------------- LOCAL ASSETS --------------------------#
flutter:
  uses-material-design: true
  assets:
    - .env
  #-------------------------- LOCAL FONTS --------------------------#
  # fonts:
  #   - family:
  #     fonts:
  #       - asset:
  #       - weight: