---
#-------------------------- BASE INFORMATION --------------------------#
name: ecos
description: "Mobile application for the Ecos system "

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

#-------------------------- PRODUCTION PACKAGES --------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  formz: ^0.8.0
  mask_text_input_formatter: ^2.9.0
  flutter_secure_storage: ^9.2.4
  go_router: ^14.8.0
  easy_localization: ^3.0.7

  # Buissnes logic
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # Network
  retrofit: ^4.4.2

  # Icons
  flutter_svg: ^2.0.17

#-------------------------- DEVELOPMENT PACKAGES --------------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.7
  json_serializable: ^6.9.3

#-------------------------- LOCAL ASSETS --------------------------#
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/l10n/
    - .env
  #-------------------------- LOCAL FONTS --------------------------#
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/static/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit/static/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/static/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/static/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit/static/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/static/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/static/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit/static/Outfit-Black.ttf
          weight: 900
